### ISSUE TITLE
Two NIC setup in linux not still not allowing guest Alpha instance to Host communication.

### ISSUE THREAD

**Issue by Vivis-wvs** [lenticularis39/axpbox#88]
Hello all,
I just installed a second NIC in the axpbox debian server I've created. I was using a single NIC with no host/guest communication, but I wanted to get that feature sorted out and decided on the two NIC approach. I've changed the NIC settings in es40.cfg to use the new NIC interface name, and while it does work, the host and the guest Alpha instance still cannot communicate.
Any ideas?

**Comment by mvorl** [comment]
This probably hasn't to do with the AXPbox code, but with the setup of the second NIC. I'm using taptap.c which sets up two TAP devices, forwarding data between them. I then configure tap0 in AXPbox and the guest OS, and tap1 in the host.

**Comment by mvorl** [comment]
OK, so I just saw the [video on Twitch](https://www.twitch.tv/videos/1694263461) with your network setup, and I think I know what's wrong. If you configure the VMS guest and the Linux host into the same IP subnet, all communication is expected to take place directly - no need to send packets to the default gateway. Try giving the VMS guest an IP in different subnet, so that the packets must pass through the default gateway.

**Comment by Vivis-wvs** [comment]
Thanks so much for the info, I found out how important the semicolon was!
